[package]
name = "keylix-oauth"
description = "OAuth integration for Keylix sender-constrained authorization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
aws-lc-rs.workspace = true
base64.workspace = true
keylix-core = { path = "../keylix-core" }
keylix-dpop = { path = "../keylix-dpop" }

[lints]
workspace = true
